version: '3'
services:
  shard1:
    container_name: shard1
    image: mongo
    command: mongod --shardsvr --replSet shard1rs --port 27017 --dbpath /data/db
    ports:
      - 20001:27017
    volumes:
      - shard1:/data/db
  shard2:
    container_name: shard2
    image: mongo
    command: mongod --shardsvr --replSet shard1rs --port 27017 --dbpath /data/db
    ports:
      - 20002:27017
    volumes:
      - shard2:/data/db
  shard3:
    container_name: shard3
    image: mongo
    command: mongod --shardsvr --replSet shard1rs --port 27017 --dbpath /data/db
    ports:
      - 20003:27017
    volumes:
      - shard3:/data/db
volumes:
  shard1: {}
  shard2: {}
  shard3: {}
