version: '3'
services:
  shard4:
    container_name: shard4
    image: mongo
    command: mongod --shardsvr --replSet shard2rs --port 27017 --dbpath /data/db
    ports:
      - 20004:27017
    volumes:
      - shard4:/data/db
  shard5:
    container_name: shard5
    image: mongo
    command: mongod --shardsvr --replSet shard2rs --port 27017 --dbpath /data/db
    ports:
      - 20005:27017
    volumes:
      - shard5:/data/db
  shard6:
    container_name: shard6
    image: mongo
    command: mongod --shardsvr --replSet shard2rs --port 27017 --dbpath /data/db
    ports:
      - 20006:27017
    volumes:
      - shard6:/data/db
volumes:
  shard4: {}
  shard5: {}
  shard6: {}
